-- Phase 2: NFL cron automation, totals picks, and result tracking.
-- Run manually against the Supabase project (no migration runner in this repo).
-- Additive only — does not alter nfl_team_elo, nfl_picks_cache, or any MLB table.

-- Per-pick row storage, mirroring MLB's model_picks shape (date, teams, pick, result,
-- features jsonb for calibration) but with an added market_type column since NFL
-- generates moneyline + spread + total picks per game, not just one market like MLB.
create table if not exists nfl_model_picks (
  id           bigint generated by default as identity primary key,
  date         text not null,
  game_id      text not null,
  market_type  text not null default 'moneyline', -- 'moneyline' | 'spread' | 'total'
  home_team    text not null,
  away_team    text not null,
  pick         text not null,
  line         numeric,      -- spread points or total points; null for moneyline
  odds         integer,
  edge         numeric,
  tier         text,
  is_bet       boolean not null default false,
  result       text not null default 'pending', -- 'pending' | 'win' | 'loss' | 'push'
  home_score   integer,
  away_score   integer,
  features     jsonb,
  resolved_at  timestamptz,
  created_at   timestamptz not null default now()
);

create index if not exists nfl_model_picks_date_idx on nfl_model_picks (date);
create index if not exists nfl_model_picks_pending_idx on nfl_model_picks (result) where result = 'pending';

-- Mirrors model_daily_stats's shape, scoped to NFL. Only counts is_bet picks,
-- same convention as MLB's dayWins/dayLosses aggregation in cron/resolve.
create table if not exists nfl_daily_stats (
  date   text primary key,
  wins   integer not null default 0,
  losses integer not null default 0
);
