-- MLB player prop picks (pitcher strikeouts, batter anytime home run).
-- Run manually against the Supabase project (no migration runner in this repo).
-- Additive only — does not alter picks_cache, model_picks, or any NFL table.

-- Fast whole-day read, mirroring picks_cache's date-keyed jsonb shape.
create table if not exists prop_picks_cache (
  date         text primary key,
  picks        jsonb not null default '[]'::jsonb,
  generated_at timestamptz not null default now()
);

-- Per-pick audit/CLV row storage, mirroring model_picks but with nfl_model_picks'
-- market_type/line columns since props — like NFL spread/total — need more than
-- one market per game.
create table if not exists prop_model_picks (
  id           bigint generated by default as identity primary key,
  date         text not null,
  event_id     text not null,
  game_id      text not null,
  market_type  text not null,               -- 'pitcher_k' | 'batter_hr'
  player_id    integer,
  player_name  text not null,
  team         text,
  opponent     text,
  home_team    text not null,
  away_team    text not null,
  line         numeric,                     -- e.g. 6.5; null for HR (implicit 0.5)
  pick         text not null,               -- 'higher' | 'lower' | 'yes' | 'no'
  odds         integer,
  model_prob   numeric,
  market_prob  numeric,
  edge         numeric,
  confidence   numeric,                     -- display % (0-100), same as model_prob*100
  bookmaker    text,
  result       text not null default 'pending', -- 'pending' | 'win' | 'loss'
  actual_value integer,                     -- backfilled Ks or HR count(0/1) on resolve
  features     jsonb,
  resolved_at  timestamptz,
  created_at   timestamptz not null default now()
);

create index if not exists prop_model_picks_date_idx on prop_model_picks (date);
create index if not exists prop_model_picks_pending_idx on prop_model_picks (result) where result = 'pending';
create index if not exists prop_model_picks_market_idx on prop_model_picks (market_type);
