-- Backtesting & calibration engine: historical replay of the production
-- probability model (lib/probability.js) and filter engine (lib/filter.js)
-- against reconstructed historical game states (2022-2024 Retrosheet).
-- Run manually against the Supabase project (no migration runner in this repo).
-- New, standalone tables — does not touch picks_cache/model_picks or any
-- live production table.

create table if not exists backtest_runs (
  id           bigint generated by default as identity primary key,
  run_at       timestamptz not null default now(),
  sport        text not null default 'mlb',
  tier         text not null,          -- 'elo_only' | 'full_replay' | 'roi_real_odds'
  season_start text,
  season_end   text,
  game_count   integer not null default 0,
  params       jsonb,                  -- elo K/home-adv, odds source, calibration split, feature toggles
  metrics      jsonb,                  -- brier, logloss, calibration buckets (pre/post isotonic), roi summary, equity curve, verdict/edge breakdowns
  notes        text
);

create table if not exists backtest_games (
  id                          bigint generated by default as identity primary key,
  run_id                      bigint not null references backtest_runs(id) on delete cascade,
  date                        text not null,
  home_team                   text not null,
  away_team                   text not null,
  home_score                  integer,
  away_score                  integer,
  home_won                    boolean,
  model_home_prob             numeric,
  model_home_prob_calibrated  numeric,
  pick                        text,
  verdict                     text,
  confidence                  numeric,
  true_edge_pct               numeric,
  market_home_implied         numeric,
  odds_source                 text,
  bet_result                  text,
  bankroll_after              numeric,
  features                    jsonb
);

create index if not exists backtest_games_run_idx     on backtest_games (run_id);
create index if not exists backtest_games_verdict_idx on backtest_games (run_id, verdict);
