-- Isotonic recalibration curve for the live probability model
-- (lib/probability.js's getCalibratedModelProbability, lib/calibration-db.js).
-- Run manually against the Supabase project (no migration runner in this repo).
-- New, standalone table — does not touch picks_cache/model_picks or any
-- other live production table.

create table if not exists model_calibration (
  id                 bigint generated by default as identity primary key,
  sport              text not null default 'mlb',
  active             boolean not null default true,
  control_points     jsonb not null,       -- [{x, y}, ...] isotonic step function, x=raw prob, y=calibrated prob
  fitted_at          timestamptz not null default now(),
  train_season_start text,
  train_season_end   text,
  game_count         integer,
  notes              text
);

-- Only one active curve per sport at a time; getCalibrationCurve() always
-- reads the most recently fitted active row.
create index if not exists model_calibration_active_idx on model_calibration (sport, active, fitted_at desc);
