-- Live weight-tuning: stores fitted WEIGHTS vectors (lib/probability.js) the
-- same way sql/009_model_calibration.sql stores isotonic curves — full
-- history via the active flag, so a tuning run can be rolled back exactly
-- like a calibration curve. Run manually against the Supabase project (no
-- migration runner in this repo, same as 009 and 010).
--
-- No row for a sport = no live override yet; lib/weights-db.js falls back to
-- the hardcoded WEIGHTS defaults in lib/probability.js, then seeds this table
-- from them on first read (mirrors lib/calibration-db.js's seed-on-read).

create table if not exists model_weights (
  id         bigint generated by default as identity primary key,
  sport      text not null default 'mlb',
  active     boolean not null default true,
  weights    jsonb not null,       -- full WEIGHTS-shaped object (partial overrides allowed)
  fitted_at  timestamptz not null default now(),
  game_count integer,              -- live picks the fit was evaluated/trained against
  notes      text
);

create index if not exists model_weights_active_idx on model_weights (sport, active, fitted_at desc);

-- Reuses model_recalibration_settings (sql/010) rather than a new table —
-- same per-sport on/off switch pattern, one more column.
alter table model_recalibration_settings
  add column if not exists auto_weights_enabled boolean not null default true;
