-- NFL fantasy draft rankings (VORP-based cheat sheet) and its backtest
-- results. Separate schema from backtest_runs/backtest_games (sql/007) since
-- those are game-outcome shaped and don't fit player-season projections.
-- Run manually against the Supabase project (no migration runner in this repo).

create table if not exists nfl_fantasy_rankings (
  id               bigint generated by default as identity primary key,
  player_id        text not null,        -- nflverse gsis_id
  espn_id          text,                 -- crosswalked, for live injury joins
  name             text not null,
  position         text not null,        -- QB | RB | WR | TE
  team             text,
  scoring_format   text not null,        -- 'ppr' | 'half_ppr' | 'standard'
  season           int not null,
  projected_points numeric,
  ceiling_points   numeric,
  floor_points     numeric,
  replacement_pts  numeric,
  vorp             numeric,
  ceiling_vorp     numeric,              -- final ranking metric (ceiling-biased)
  rank_overall     int,
  rank_position    int,
  tier             int,
  injury_status    text,
  injury_risk      text,                 -- low | medium | high (historical durability)
  updated_at       timestamptz not null default now(),
  unique (player_id, scoring_format, season)
);

create index if not exists nfl_fantasy_rankings_rank_idx on nfl_fantasy_rankings (scoring_format, season, rank_overall);
create index if not exists nfl_fantasy_rankings_pos_idx  on nfl_fantasy_rankings (position, scoring_format, season);

create table if not exists nfl_fantasy_backtest_runs (
  id             bigint generated by default as identity primary key,
  run_at         timestamptz not null default now(),
  target_season  int not null,
  scoring_format text not null,
  params         jsonb,
  metrics        jsonb,
  notes          text
);

create table if not exists nfl_fantasy_backtest_players (
  id                      bigint generated by default as identity primary key,
  run_id                  bigint not null references nfl_fantasy_backtest_runs(id) on delete cascade,
  player_id               text,
  name                    text,
  position                text,
  predicted_rank_position int,
  predicted_ceiling_vorp  numeric,
  actual_points           numeric,
  actual_rank_position    int,
  actual_vorp             numeric,
  tier                    int
);

create index if not exists nfl_fantasy_backtest_players_run_idx on nfl_fantasy_backtest_players (run_id);
