-- Feed adapter Phase 0: credit-safety infrastructure. Additive only — no existing
-- table (picks_cache, model_picks, prop_picks_cache, prop_model_picks) is touched.
-- Run manually against the Supabase project (no migration runner in this repo).
-- Backs lib/feed-adapter/{credit-log,lease-lock,mlb-props}.js.

-- Predicted-vs-actual credit accounting. Every adapter fetch logs its own pre-fetch
-- estimate; actual_used/actual_remaining come from The Odds API's x-requests-used/
-- x-requests-remaining response headers when available. Both null is expected for
-- non-TOA sources (e.g. ESPN doesn't bill credits) — that's a source difference,
-- not a logging bug.
create table if not exists odds_credit_log (
  id               bigint generated by default as identity primary key,
  adapter_key      text not null,
  estimated        integer not null,
  actual_used      integer,
  actual_remaining integer,
  created_at       timestamptz not null default now()
);

create index if not exists odds_credit_log_adapter_idx on odds_credit_log (adapter_key, created_at desc);

-- Cross-instance lease row for de-duping concurrent external (credit-costed) fetches
-- across Vercel serverless instances. Deliberately NOT a Postgres advisory lock:
-- acquiring one would hold a pooled connection open for the full duration of the
-- external HTTP call to The Odds API, and through Supabase's transaction-mode pooler
-- that starves the connection pool under exactly the concurrency this is meant to
-- protect against. See lib/feed-adapter/lease-lock.js.
create table if not exists odds_fetch_leases (
  lease_key  text primary key,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

-- Atomic "acquire only if free or expired" upsert. A plain PostgREST upsert can't
-- express the conditional WHERE below, so this is a real function — the
-- ON CONFLICT ... WHERE clause is what makes acquisition race-safe under genuinely
-- concurrent callers (two lambdas racing this at once never both succeed).
create or replace function acquire_odds_lease(p_key text, p_ttl_seconds integer)
returns boolean
language plpgsql
as $$
declare
  v_count integer;
begin
  insert into odds_fetch_leases (lease_key, expires_at)
  values (p_key, now() + make_interval(secs => p_ttl_seconds))
  on conflict (lease_key) do update
    set expires_at = excluded.expires_at
    where odds_fetch_leases.expires_at < now();
  get diagnostics v_count = row_count;
  return v_count > 0;
end;
$$;

-- Cross-instance cache for per-event player-props responses. lib/odds-props.js's own
-- cache is an in-memory Map, per Vercel instance — same limitation lib/odds.js's cache
-- has (see the credit-adapter plan notes). Lease losers read this table on a cold
-- in-memory cache instead of falling through to a second live (credit-costed) fetch.
create table if not exists odds_props_cache (
  event_id   text primary key,
  payload    jsonb not null,
  fetched_at timestamptz not null default now()
);
