-- Stores per-player weekly schedule-difficulty data extracted from uploaded
-- screenshots (see app/api/admin/fantasy-schedule-import/route.js) — matched
-- by player name rather than player_id, since a screenshot carries no stable
-- ID. Re-uploading the same player/season/week replaces the prior row.
-- Applied via `npm run migrate` (scripts/migrate.js), tracked in schema_migrations.

create table if not exists nfl_fantasy_schedule_difficulty (
  id           bigint generated by default as identity primary key,
  player_name  text not null,
  position     text,
  season       int not null,
  week         int not null,
  opponent     text,
  difficulty   text not null,        -- 'easy' | 'neutral' | 'hard' | 'bye'
  source       text,                 -- uploaded filename/label, for provenance
  uploaded_at  timestamptz not null default now(),
  unique (player_name, season, week)
);

create index if not exists nfl_fantasy_schedule_difficulty_lookup_idx
  on nfl_fantasy_schedule_difficulty (player_name, season);
