-- Stores per-team projected personnel-usage data (e.g. % of snaps in 3+ WR
-- sets vs 2-or-fewer WR sets) extracted from uploaded screenshots (see
-- app/api/admin/fantasy-personnel-import/route.js). A season-long team
-- tendency, not a weekly one, so it's keyed by team+season and re-uploading
-- replaces the prior row. Also adds a display-only note column to
-- nfl_fantasy_rankings (sql/012_nfl_fantasy.sql) for the Cheat Sheet badge.
-- Applied via `npm run migrate` (scripts/migrate.js), tracked in schema_migrations.

create table if not exists nfl_fantasy_team_personnel (
  id            bigint generated by default as identity primary key,
  team          text not null,
  season        int not null,
  wr3_plus_pct  numeric not null,   -- % of snaps in 3+ WR sets
  wr2_minus_pct numeric not null,   -- % of snaps in 2-or-fewer WR sets
  source        text,               -- uploaded filename/label, for provenance
  uploaded_at   timestamptz not null default now(),
  unique (team, season)
);

alter table nfl_fantasy_rankings add column if not exists personnel_note text;
