-- One connected Sleeper league per app user, so "My Team" doesn't require
-- re-entering a username every visit. Deliberately single-row-per-user (not
-- one-to-many) for v1 — connecting a new league replaces the old one, same
-- "one text field" simplicity as the initial connect flow.
-- Rosters themselves are NOT cached here: they're fetched live from Sleeper
-- on every read (lib/nfl-fantasy/roster.js) since a roster changes via
-- waivers/trades far more often than a user would hit this page, and the
-- Sleeper league/roster endpoints are small enough to not need the caching
-- discipline the full player map (lib/nfl-fantasy/sleeper.js) requires.
-- Run manually against the Supabase project (no migration runner in this repo).

create table if not exists sleeper_connections (
  id                bigint generated by default as identity primary key,
  user_id           text not null,
  sleeper_user_id   text not null,
  sleeper_username  text,
  league_id         text not null,
  league_name       text,
  season            text,
  roster_id         int,
  team_name         text,
  connected_at      timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (user_id)
);
