-- In-season fantasy tracker: a per-user watchlist with weekly difficulty vs.
-- actual-performance tracking, a manual "gut check" rating log, and an
-- injury-transition history used to power the teammate-usage-shift alerts
-- (see lib/nfl-fantasy/teammate-impact.js). Companion to the draft-time
-- cheat sheet in sql/012-016 — that side stays season-long/overwrite-in-place;
-- these tables are the first to carry real week-over-week history.
--
-- Two different player-id spaces are in play throughout this app (see
-- lib/nfl-fantasy/id-map.js's header comment): nflverse's gsis_id (used by
-- nfl_fantasy_rankings.player_id and computed weekly stats) and ESPN's
-- athlete id (used by player_index.player_id and everything injury/roster
-- related, incl. the /api/search typeahead the UI adds players from). To
-- keep that explicit rather than reusing the ambiguous "player_id" name,
-- tables here use `espn_id` for the ESPN-space id and `player_id` only
-- where it's genuinely the nflverse gsis_id (nfl_fantasy_weekly_actual,
-- matching nfl_fantasy_rankings' existing convention).
--
-- Run manually against the Supabase project (no migration runner in this repo).

create table if not exists nfl_fantasy_tracked_players (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  espn_id     text not null,       -- id returned by /api/search?sport=nfl (player_index space)
  player_id   text,                 -- resolved nflverse gsis_id (nfl_fantasy_rankings.player_id), nullable until resolved
  name        text not null,
  position    text,
  team        text,
  created_at  timestamptz not null default now(),
  unique (user_id, espn_id)
);

create table if not exists nfl_fantasy_gut_check (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  espn_id     text not null,
  player_name text not null,
  season      int not null,
  week        int not null,
  rating      int not null check (rating between 1 and 5),
  note        text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (user_id, espn_id, season, week)
);

create table if not exists nfl_fantasy_weekly_actual (
  id             bigint generated by default as identity primary key,
  player_id      text not null,     -- nflverse gsis_id
  name           text,
  season         int not null,
  week           int not null,
  scoring_format text not null,     -- 'ppr' | 'half_ppr' | 'standard'
  actual_points  numeric not null,
  opponent       text,
  updated_at     timestamptz not null default now(),
  unique (player_id, season, week, scoring_format)
);

create index if not exists nfl_fantasy_weekly_actual_lookup_idx
  on nfl_fantasy_weekly_actual (player_id, season);

-- Append-only injury status transition log, populated by
-- app/api/cron/player-index diffing each day's ESPN pull against the
-- previous stored status. Powers both the news feed and teammate-impact
-- detection (grouping by team+position at read time — no derived table for
-- that, so the heuristic can change without a backfill).
create table if not exists nfl_fantasy_injury_log (
  id          bigint generated by default as identity primary key,
  espn_id     text not null,
  name        text not null,
  team        text,
  position    text,
  old_status  text,
  new_status  text,
  changed_at  timestamptz not null default now(),
  season      int not null
);

create index if not exists nfl_fantasy_injury_log_recent_idx
  on nfl_fantasy_injury_log (changed_at desc);

create index if not exists nfl_fantasy_injury_log_team_idx
  on nfl_fantasy_injury_log (team, changed_at desc);
