-- Every Start/Sit head-to-head probability call (lib/nfl-fantasy/probability.js),
-- whether generated by the historical backtest (source='backtest', seeded so
-- the public calibration page isn't empty on day one) or by a real user
-- hitting the live Start/Sit tool (source='live', app/api/nfl/fantasy/route.js).
-- This is the fantasy analog of model_picks/model_calibration (sql/009) for
-- the betting-picks product: app/api/nfl/fantasy/calibration/route.js reads
-- resolved rows from here to answer "does our 63% actually hit 63%?"
--
-- Live rows are inserted unresolved (resolved=false, actual_* / week null) —
-- there's no live weekly-fantasy-points source wired yet to grade them
-- automatically, so they sit here as a record of what the model told real
-- users until a resolution job exists to fill in the actual_* columns.
-- Run manually against the Supabase project (no migration runner in this repo).

create table if not exists fantasy_probability_log (
  id                bigint generated by default as identity primary key,
  source            text not null,        -- 'backtest' | 'live'
  scoring_format    text not null,
  season            int not null,
  week              int,                  -- null for live rows until a resolution job exists
  position          text,                 -- null when playerA/playerB differ in position
  player_a_id       text,                 -- nflverse gsis_id, when known
  player_a_name     text not null,
  player_b_id       text,
  player_b_name     text not null,
  predicted_prob_a  numeric not null,     -- 0-100, P(player A outscores player B) at call time
  actual_points_a   numeric,
  actual_points_b   numeric,
  actual_winner     text,                 -- 'A' | 'B' | 'push', null until resolved
  resolved          boolean not null default false,
  created_at        timestamptz not null default now()
);

create index if not exists fantasy_probability_log_resolved_idx on fantasy_probability_log (resolved, scoring_format);
create index if not exists fantasy_probability_log_season_week_idx on fantasy_probability_log (season, week);
