-- The pitch's "log the gut, don't fight it" piece: a personal record of
-- which player a user actually says they're starting, captured alongside
-- what the model said at that moment, so the season-end "you vs the model"
-- comparison (the retention/screenshot hook) has real data to work from.
-- Distinct from fantasy_probability_log (sql/018), which is the MODEL's own
-- aggregate track record across all users — this is per-user.
--
-- Resolution shares the same gap as fantasy_probability_log's 'live' rows:
-- no live per-week fantasy-points source is wired up yet, so actual_* /
-- resolved fill in once that job exists. week is null for the same reason
-- (no current-NFL-week helper yet).
-- Run manually against the Supabase project (no migration runner in this repo).

create table if not exists fantasy_gut_calls (
  id                bigint generated by default as identity primary key,
  user_id           text not null,
  scoring_format    text not null,
  season            int not null,
  week              int,
  player_a_id       text,
  player_a_name     text not null,
  player_b_id       text,
  player_b_name     text not null,
  model_prob_a      numeric not null,    -- model's P(A) at the moment this was logged
  model_pick        text not null,       -- 'A' | 'B' — whichever the model favored
  gut_pick          text not null,       -- 'A' | 'B' — whichever the user actually said they're starting
  actual_points_a   numeric,
  actual_points_b   numeric,
  actual_winner     text,                -- 'A' | 'B' | 'push', null until resolved
  resolved          boolean not null default false,
  created_at        timestamptz not null default now()
);

create index if not exists fantasy_gut_calls_user_idx on fantasy_gut_calls (user_id, created_at desc);
