-- Average draft position (ADP) from Fantasy Football Calculator's free API
-- (fantasyfootballcalculator.com/api/v1/adp/ppr), joined against
-- nfl_fantasy_rankings (sql/012_nfl_fantasy.sql) to show "our rank vs
-- market ADP" on the draft cheat sheet. Run manually against the Supabase
-- project (no migration runner in this repo).
--
-- v1 is PPR-only (scoring_format is still part of the key so half-PPR/
-- standard can be added later without a migration). teams is in the key
-- too, defaulted to 12, so a future league-size param doesn't collide.
--
-- player_id is nullable: FFC rows that don't match this app's player index
-- (DEF/K, or gaps in the index) are still stored rather than dropped, same
-- philosophy as lib/nfl-fantasy/id-map.js's crosswalk fallback.

create table if not exists nfl_fantasy_adp (
  id                bigint generated by default as identity primary key,
  ffc_player_id     text not null,        -- FFC's own id; stable upsert key even when unmatched
  player_id         text,                 -- resolved nflverse gsis_id via name/position match, null if unmatched
  name              text not null,        -- as reported by FFC
  position          text not null,
  team              text,
  scoring_format    text not null,        -- 'ppr' for v1
  season            int not null,
  teams             int not null default 12,
  adp               numeric,
  adp_position_rank int,                  -- rank within position, computed over ALL fetched FFC rows for that position (not just matched ones)
  adp_high          int,
  adp_low           int,
  times_drafted     int,
  updated_at        timestamptz not null default now(),
  unique (season, scoring_format, teams, ffc_player_id)
);

create index if not exists nfl_fantasy_adp_player_idx on nfl_fantasy_adp (player_id, scoring_format, season, teams);
