-- Per-user custom prop lines (the Prop Lines tab's slider), keyed to a
-- specific day's cached pick rather than prop_model_picks.id — the trending
-- pick a user actually sees comes from prop_picks_cache's jsonb `picks`
-- array, which doesn't carry a prop_model_picks row id back with it.
-- Applied via `npm run migrate` (scripts/migrate.js), tracked in schema_migrations.

create table if not exists user_prop_lines (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null,
  date         text not null,
  player_id    text not null,
  market_type  text not null,
  custom_line  numeric not null,
  updated_at   timestamptz not null default now(),
  unique (user_id, date, player_id, market_type)
);

create index if not exists user_prop_lines_user_date_idx on user_prop_lines (user_id, date);
