-- Market consensus ADP (average draft position), pasted in by an admin from
-- any public source (FantasyPros/Sleeper/ESPN — no scraping, no API key —
-- see lib/nfl-fantasy/adp-extract.js) and joined into nfl_fantasy_rankings
-- by name so the Cheat Sheet can show our rank against where the market is
-- actually drafting each player. Run manually against the Supabase project
-- (no migration runner in this repo).

create table if not exists nfl_fantasy_adp (
  id         bigint generated by default as identity primary key,
  name       text not null,
  position   text,                 -- QB | RB | WR | TE | K | DST, when the source provides one
  team       text,
  adp        numeric not null,
  season     int not null,
  source     text,                 -- free-text provenance, e.g. "FantasyPros PPR overall, pasted 2026-08-07"
  updated_at timestamptz not null default now(),
  unique (name, season)
);

create index if not exists nfl_fantasy_adp_season_idx on nfl_fantasy_adp (season);

alter table nfl_fantasy_rankings add column if not exists adp numeric;
alter table nfl_fantasy_rankings add column if not exists adp_diff numeric;
