-- Time-series odds capture for the "stock chart" feature — odds/implied
-- probability over time per game/market/side, not just a single closing
-- snapshot (see sql/... snapshot cron's CLV tracking, which upserts one
-- point; this appends many). Sport/market-agnostic: one row per
-- sport+game+market+side+poll, so MLB moneyline and NFL moneyline/spread/
-- total all land in the same table without separate schemas.
-- Run manually against the Supabase project (no migration runner in this repo).

create table if not exists odds_history (
  id            bigint generated by default as identity primary key,
  sport         text not null,        -- 'mlb' | 'nfl'
  game_id       text not null,        -- id from the odds source, stable across polls for the same game
  home_team     text not null,
  away_team     text not null,
  commence_time timestamptz,
  market        text not null,        -- 'moneyline' | 'spread' | 'total'
  side          text not null,        -- 'home' | 'away' | 'over' | 'under'
  line          numeric,              -- spread points / total points; null for moneyline
  odds          int,                  -- american odds
  implied_prob  numeric,              -- vig-removed fair implied probability, when available
  captured_at   timestamptz not null default now()
);

create index if not exists odds_history_chart_idx on odds_history (sport, game_id, market, side, captured_at);

-- No default retention job in this repo (no migration runner / scheduled
-- SQL here) — prune manually or via the poller script, e.g.:
--   delete from odds_history where captured_at < now() - interval '45 days';
