-- Lightweight self-logged error table for the admin System tab (app/admin/page.js).
-- Vercel Hobby doesn't expose durable, queryable runtime logs via API (that needs
-- Log Drains, a Pro-plan feature), so routes call lib/error-log.js to record their
-- own failures here instead of relying on pulling logs from Vercel.
-- Run manually against the Supabase project (no migration runner in this repo).

create table if not exists error_log (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source     text not null,
  route      text,
  message    text not null,
  meta       jsonb
);

create index if not exists error_log_created_at_idx on error_log (created_at desc);
create index if not exists error_log_source_idx on error_log (source);
