-- Quota snapshots captured off real The Odds API responses (see lib/quota-log.js) —
-- not a dedicated probe, so reading this doesn't itself spend quota. Backs the
-- burn-rate trend on the admin Rate Limits tab (app/admin/page.js), which is what
-- would have caught THE_ODDS_API_KEY running out before it actually hit zero.
-- Applied via `npm run migrate` (scripts/migrate.js), tracked in schema_migrations.

create table if not exists api_quota_log (
  id                 bigint generated by default as identity primary key,
  source             text not null,
  requests_remaining int,
  requests_used      int,
  recorded_at        timestamptz not null default now()
);

create index if not exists api_quota_log_source_time_idx on api_quota_log (source, recorded_at desc);
