-- Daily-refreshed nflverse tables for the current NFL season, populated by
-- /api/cron/nflverse-ingest. Distinct from data/nflverse/*.json (see
-- scripts/nfl-fantasy/fetch-nflverse.js), which is a checked-in bulk dump of
-- the last 5 *completed* seasons used as a stable projection baseline —
-- prior seasons never change, so that stays a manual/off-season pull. These
-- tables hold the in-progress season, which updates weekly as games are
-- played, so it needs a real daily job.
--
-- All four tables share `player_id`, resolved through nflverse's players.csv
-- crosswalk (lib/nfl-fantasy/id-map.js) the same way the rest of the app
-- joins nflverse data to ESPN/Sleeper. player_id is `gsis_id` wherever the
-- crosswalk resolves one; snap_counts has no gsis_id column of its own, so
-- unresolved rows there fall back to a `pfr:<pfr_id>` or `name:<normalized
-- name>` synthetic key rather than being dropped (nflverse.gsisIdForName /
-- gsisIdForPfrId in id-map.js, same "don't erase a real player" posture
-- documented at the top of that file).
-- Applied via `npm run migrate` (scripts/migrate.js), tracked in schema_migrations.

create table if not exists nfl_fantasy_players (
  gsis_id    text primary key,
  espn_id    text,
  pfr_id     text,
  name       text not null,
  position   text,
  team       text,
  updated_at timestamptz not null default now()
);

create index if not exists nfl_fantasy_players_pfr_idx on nfl_fantasy_players (pfr_id);

create table if not exists nfl_fantasy_stats_player (
  id                bigint generated by default as identity primary key,
  player_id         text not null,        -- resolved gsis_id
  season            int not null,
  week              int not null,
  name              text,
  position          text,
  team              text,
  completions       numeric,
  attempts          numeric,
  passing_yards     numeric,
  passing_tds       numeric,
  interceptions     numeric,
  carries           numeric,
  rushing_yards     numeric,
  rushing_tds       numeric,
  receptions        numeric,
  targets           numeric,
  receiving_yards   numeric,
  receiving_tds     numeric,
  fantasy_points     numeric,
  fantasy_points_ppr numeric,
  updated_at        timestamptz not null default now(),
  unique (player_id, season, week)
);

create index if not exists nfl_fantasy_stats_player_season_idx on nfl_fantasy_stats_player (season, week);

create table if not exists nfl_fantasy_snap_counts (
  id            bigint generated by default as identity primary key,
  player_id     text not null,        -- resolved gsis_id, or pfr:/name: fallback key — see header
  season        int not null,
  week          int not null,
  name          text,
  position      text,
  team          text,
  offense_snaps numeric,
  offense_pct   numeric,
  defense_snaps numeric,
  defense_pct   numeric,
  st_snaps      numeric,
  st_pct        numeric,
  updated_at    timestamptz not null default now(),
  unique (player_id, season, week)
);

create index if not exists nfl_fantasy_snap_counts_season_idx on nfl_fantasy_snap_counts (season, week);

-- Passing/rushing/receiving Next Gen Stats each carry a different metric
-- set (avg_time_to_throw vs. avg_separation vs. ...) — one jsonb `metrics`
-- column avoids ~30 columns that are sparse-by-construction (a receiving row
-- would never populate the passing-only fields, and vice versa), matching
-- the jsonb precedent already used for run-shaped data in
-- nfl_fantasy_backtest_runs (sql/007_backtest.sql).
create table if not exists nfl_fantasy_nextgen_stats (
  id         bigint generated by default as identity primary key,
  player_id  text not null,        -- resolved gsis_id
  season     int not null,
  week       int not null,
  stat_type  text not null,        -- 'passing' | 'rushing' | 'receiving'
  name       text,
  team       text,
  metrics    jsonb,
  updated_at timestamptz not null default now(),
  unique (player_id, season, week, stat_type)
);

create index if not exists nfl_fantasy_nextgen_stats_season_idx on nfl_fantasy_nextgen_stats (season, week, stat_type);
