-- Server-side save for the Draft Assistant (components/NFLSection.js, Fantasy
-- tab). Previously "Save Team" only wrote to localStorage (see the
-- DRAFT_STORAGE_KEY comment that used to live in NFLSection.js) — fine for
-- surviving a reload, but it didn't follow you to another device/browser and
-- there was no way to track more than one draft (e.g. two different
-- leagues) at a time. This table is the account-scoped replacement: each row
-- is one named, saved snapshot of a draft in progress (or finished).
--
-- No RLS here — same posture as user_prop_lines (sql/019) and
-- fantasy_free_usage (sql/017): every access goes through an API route using
-- requireAuth() (lib/auth.js) plus the service-role key, with ownership
-- enforced by the route's own `.eq("user_id", user.id)` filter rather than a
-- Postgres policy. The one exception is the public share link, which reads
-- by share_token with no user_id filter at all — that's the point of a
-- share link, and share_token is an unguessable random value, not something
-- an attacker can enumerate.
-- Applied via `npm run migrate` (scripts/migrate.js), tracked in schema_migrations.

create table if not exists nfl_fantasy_draft_teams (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null,
  name            text not null default 'My Team',
  scoring_format  text not null default 'ppr',
  drafted_ids     jsonb not null default '[]'::jsonb,  -- every player_id off the board when saved (mine + everyone else's) — reloading this snapshot needs the full picture, not just mine, so "available" stays correct
  my_ids          jsonb not null default '[]'::jsonb,  -- subset that's mine — what MyTeamLineup renders
  share_token     text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists nfl_fantasy_draft_teams_user_idx on nfl_fantasy_draft_teams (user_id, updated_at desc);
create unique index if not exists nfl_fantasy_draft_teams_share_idx on nfl_fantasy_draft_teams (share_token) where share_token is not null;
