-- Bet Slip Tracker: user uploads a screenshot of a sportsbook or Kalshi bet
-- slip, Claude vision (lib/bets/parse-slip.js, called from
-- app/api/bets/route.js) extracts the structured contents, and it's saved
-- here for later tracking. Free for every tier — the API route doesn't call
-- requirePro().
--
-- Unlike most tables in this app (see sql/028's note on the no-RLS
-- convention — every other table is only ever touched via the service-role
-- key with the route's own `.eq("user_id", ...)` filter as the ownership
-- check), bet_slips/bet_legs use real Postgres RLS. app/api/bets/route.js
-- talks to these two tables through a per-request Supabase client
-- authenticated with the *user's own* JWT (anon key + `Authorization: Bearer
-- <token>`), not the service-role key, so RLS is the actual enforcement
-- boundary here rather than a convention the route has to remember to
-- honor. insert_bet_slip() below is SECURITY INVOKER (the default, but
-- spelled out) for the same reason: it must run as the calling user so the
-- insert policies apply, not as a bypass.
--
-- bet_slip_usage (the daily upload-attempt counter) is the opposite: it's
-- internal bookkeeping never read by a user-scoped client, so it follows the
-- ordinary no-RLS convention and is only ever touched with the service-role
-- key from app/api/bets/route.js.
-- Applied via `npm run migrate` (scripts/migrate.js), tracked in schema_migrations.

create table if not exists bet_slips (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  book        text not null,
  ticket_id   text not null,
  stake       numeric,
  max_payout  numeric,
  placed_at   timestamptz,
  status      text not null default 'open' check (status in ('open', 'won', 'lost', 'cashed_out', 'void')),
  pnl         numeric,
  created_at  timestamptz not null default now(),
  unique (user_id, book, ticket_id)
);

create table if not exists bet_legs (
  id            bigint generated by default as identity primary key,
  slip_id       bigint not null references bet_slips(id) on delete cascade,
  sport         text,
  pick          text not null,
  implied_prob  numeric check (implied_prob is null or (implied_prob >= 0 and implied_prob <= 1)),
  close_prob    numeric check (close_prob is null or (close_prob >= 0 and close_prob <= 1)), -- filled in later for CLV tracking, not at upload time
  result        text
);

create index if not exists bet_slips_user_idx on bet_slips (user_id, created_at desc);
create index if not exists bet_legs_slip_idx on bet_legs (slip_id);

alter table bet_slips enable row level security;
alter table bet_legs  enable row level security;

create policy bet_slips_select_own on bet_slips for select using (auth.uid() = user_id);
create policy bet_slips_insert_own on bet_slips for insert with check (auth.uid() = user_id);
create policy bet_slips_update_own on bet_slips for update using (auth.uid() = user_id);
create policy bet_slips_delete_own on bet_slips for delete using (auth.uid() = user_id);

create policy bet_legs_select_own on bet_legs for select using (
  exists (select 1 from bet_slips s where s.id = bet_legs.slip_id and s.user_id = auth.uid())
);
create policy bet_legs_insert_own on bet_legs for insert with check (
  exists (select 1 from bet_slips s where s.id = bet_legs.slip_id and s.user_id = auth.uid())
);
create policy bet_legs_update_own on bet_legs for update using (
  exists (select 1 from bet_slips s where s.id = bet_legs.slip_id and s.user_id = auth.uid())
);
create policy bet_legs_delete_own on bet_legs for delete using (
  exists (select 1 from bet_slips s where s.id = bet_legs.slip_id and s.user_id = auth.uid())
);

-- Inserts a slip and all its legs atomically. Always writes auth.uid() as
-- the owner — never the caller-supplied value — so this can't be used to
-- write a slip into someone else's account even if p_slip carried a
-- user_id. SECURITY INVOKER means it runs as whatever role called it: a
-- service-role caller has no auth.uid() and the insert simply fails the
-- not-null/RLS check, so this only works from the user-scoped client.
create or replace function insert_bet_slip(p_slip jsonb)
returns bigint
language plpgsql
security invoker
as $$
declare
  v_slip_id bigint;
  v_leg     jsonb;
begin
  insert into bet_slips (user_id, book, ticket_id, stake, max_payout, placed_at, status)
  values (
    auth.uid(),
    p_slip->>'book',
    p_slip->>'ticket_id',
    (p_slip->>'stake')::numeric,
    (p_slip->>'max_payout')::numeric,
    (p_slip->>'placed_at')::timestamptz,
    coalesce(p_slip->>'status', 'open')
  )
  returning id into v_slip_id;

  for v_leg in select * from jsonb_array_elements(coalesce(p_slip->'legs', '[]'::jsonb))
  loop
    insert into bet_legs (slip_id, sport, pick, implied_prob)
    values (
      v_slip_id,
      v_leg->>'sport',
      v_leg->>'pick',
      (v_leg->>'implied_prob')::numeric
    );
  end loop;

  return v_slip_id;
end;
$$;

-- Daily upload-attempt counter (20/day, every attempt counts — see
-- app/api/bets/route.js). Same atomic check-and-increment idiom as
-- increment_fantasy_usage (sql/017_fantasy_free_usage.sql), kept in its own
-- table rather than reusing fantasy_free_usage's rows so bet-slip attempts
-- and NFL fantasy Start/Sit calls don't share a quota for the same
-- user+date.
create table if not exists bet_slip_usage (
  user_id        uuid not null,
  day            date not null,
  attempt_count  int not null default 0,
  updated_at     timestamptz not null default now(),
  primary key (user_id, day)
);

create or replace function increment_bet_slip_usage(p_user_id uuid, p_day date, p_limit int)
returns table(allowed boolean, attempt_count int) as $$
declare
  v_count int;
begin
  insert into bet_slip_usage as b (user_id, day, attempt_count, updated_at)
  values (p_user_id, p_day, 1, now())
  on conflict (user_id, day) do update
    set attempt_count = b.attempt_count + 1, updated_at = now()
    where b.attempt_count < p_limit
  returning b.attempt_count into v_count;

  if v_count is null then
    select b.attempt_count into v_count from bet_slip_usage b
      where b.user_id = p_user_id and b.day = p_day;
    return query select false, coalesce(v_count, 0);
  else
    return query select true, v_count;
  end if;
end;
$$ language plpgsql;
